In [1]:
import pandas as pd
import numpy as np

In [3]:
path = 'data/svmguide3.csv'

In [10]:
fw = pd.read_csv(path)
print(fw)

           att_1        att_2       att_3        att_4       att_5  \
0     0 0.064284  1 -0.000885  2 0.000072  3 -0.263788  4 0.003891   
1     0 0.041428  1 -0.003728  2 0.001009  3 -0.019577  4 0.001843   
2     0 0.035714  1 -0.006948   2 0.00396  3 -0.290222  4 0.059114   
3     0 0.034285   1 -0.00541  2 0.002529  3 -0.022105  4 0.003653   
4     0 0.112857  1 -0.009484  2 0.002335  3 -0.114113  4 0.010015   
...          ...          ...         ...          ...         ...   
1238  0 0.155713  1 -0.059213  2 0.044411  3 -0.415298   4 0.11249   
1239  0 0.237145   1 -0.04523  2 0.018895  3 -0.548503   4 0.08228   
1240  0 0.042857  1 -0.050936  2 0.121772  3 -0.185244  4 0.160706   
1241  0 0.125714   1 -0.06866  2 0.074968  3 -0.289851  4 0.114853   
1242  0 0.172854  1 -0.040135  2 0.019821  3 -0.076399  4 0.013637   

            att_6       att_7        att_8       att_9 att_10  ...  \
0     5 -0.000029  6 0.108449  7 -0.000575  8 0.000011    9 1  ...   
1     5 -0.000046  

In [9]:
f = open(path)

lines = f.readlines()
f.close()
tmp = [lines[0]]


for line in lines[1:]:  
    tmp_line = ["" for i in lines[0].split(',')]

    items = line.split(',')
    for item in items:
        idx, val = item.split(' ')
        idx = eval(idx)
        tmp_line[idx] = val
        
    tmp_s = ','.join(tmp_line)
    tmp.append(tmp_s)

f = open('./hh.csv', 'w')
f.writelines(tmp)

In [25]:
import utils

data_set = utils.DataLoader('./data')

x, y = data_set.load_data('svmguide3')
x[x != x] = 0
print(x[0], y[0])


[Log] load  x as (1234, 21), y as (1234,)
[ 6.42840e-02 -8.85000e-04  7.20000e-05 -2.63788e-01  3.89100e-03
 -2.90000e-05  1.08449e-01 -5.75000e-04  1.10000e-05  1.00000e+00
  0.00000e+00  7.97863e-01  5.09888e-01  0.00000e+00  1.00000e-01
  5.32533e-01  1.49772e-01  2.85714e-01  1.65124e-01  7.43000e-04
  0.00000e+00] -1.0


In [6]:
x = np.ones((1, 2))
y = np.zeros((1, 3))

z = np.concatenate((x, y), axis=1)
print(z.shape)


(1, 5)


In [42]:
x = np.random.choice([0, 1], size=(3, 5), p=[1/5, 1-1/5])
print(x)

[[1 1 0 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]]


In [44]:
idx = (x[:, 0] > 0) * (x[:, 1] > 0)
tmp = np.ones((1, 5))
print(idx)
print(idx == 0)
# print(x[idx.T, :])
# print(np.concatenate((x, tmp), axis=0))

[ True False  True]
[False  True False]


In [25]:
len(idx)

3

In [28]:
x = np.zeros(3)
x = x[..., np.newaxis]
print(x.shape)
print(x)

(3, 1)
[[0.]
 [0.]
 [0.]]


In [35]:
x = np.zeros(3)
x = x[..., np.newaxis].T
print(x)

[[0. 0. 0.]]


In [40]:
np.random.choice([0, 1], size=(1, 5), p=[1 / 5, 1 - 1 / 5])

array([[1, 1, 1, 1, 1]])

In [45]:
import random
x = [[1], [2]]
print(random.choice(x))

[1]


In [1]:
x = {}
x[1] = 0

{1: 0}
